"""
ChaosMonkey AI - Remediation Report Generator

Generates structured remediation reports for IBM Bob analysis.
"""

import json
from pathlib import Path
from typing import Dict, Any, Optional, Tuple
from datetime import datetime

from chaosmonkey.core.models import CrashReport


def generate_chaos_report(
    target_function: str,
    crashing_payload: Dict[str, Any],
    crash_report: CrashReport,
    target_file: str = "target_app.py",
    output_path: str = "CHAOS_REPORT.md",
    auto_invoke_bob: bool = True,
    bob_timeout: int = 120
) -> Tuple[str, Optional[str]]:
    """
    Generate a structured chaos report for IBM Bob analysis.
    
    Optionally invokes Bob CLI automatically to generate remediation analysis.
    
    Args:
        target_function: Name of the target function that crashed
        crashing_payload: The payload that caused the crash
        crash_report: CrashReport with error details
        target_file: Path to the target file (default: target_app.py)
        output_path: Where to write the report (default: CHAOS_REPORT.md)
        auto_invoke_bob: Whether to automatically invoke Bob CLI (default: True)
        bob_timeout: Timeout for Bob CLI invocation in seconds (default: 120)
        
    Returns:
        Tuple of (report_path, remediation_path)
        - report_path: Path to the generated crash report
        - remediation_path: Path to remediation report (None if Bob not invoked)
    """
    
    # Extract suspected weak assumption from error
    suspected_assumption = _infer_weak_assumption(crash_report)
    
    # Format the report
    report_content = f"""# ChaosMonkey Crash Report

**Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}

---

## 🎯 Target Function

**Function:** `{target_function}`  
**File:** `{target_file}`

---

## 💥 Crash Details

### Error Type
```
{crash_report.error_type}
```

### Error Message
```
{crash_report.error_message}
```

### Crashing Payload
```json
{json.dumps(crashing_payload, indent=2)}
```

---

## 📊 Traceback

```python
{crash_report.traceback}
```

---

## 🔍 Suspected Weak Assumption

{suspected_assumption}

---

## 🤖 Prompt for IBM Bob

Please analyze this crash and help fix the issue:

### Task

1. **Inspect the target file** (`{target_file}`)
   - Review the `{target_function}` function implementation
   - Identify the code path that leads to the crash

2. **Explain the root cause**
   - What assumption does the code make that fails with the crashing payload?
   - Why does this specific payload trigger the error?
   - What input validation or defensive checks are missing?

3. **Write a regression test**
   - Create a test case that reproduces this crash
   - The test should use the crashing payload shown above
   - Include assertions to verify the fix prevents this crash

4. **Propose a minimal safe fix**
   - Suggest the smallest code change that prevents this crash
   - Ensure the fix handles edge cases (null, missing keys, wrong types)
   - Preserve existing functionality for valid inputs
   - Consider blast radius: what other code might be affected?

### Context

- **Error Type:** {crash_report.error_type}
- **Error Message:** {crash_report.error_message}
- **Suspected Issue:** {suspected_assumption}

### Expected Output

Please provide:
1. Root cause explanation (2-3 sentences)
2. Regression test code (Python)
3. Minimal fix (code diff or complete function)
4. Blast radius assessment (what else might break?)

---

*This report was generated by ChaosMonkey AI - an autonomous chaos engineering platform.*
"""
    
    # Write crash report to file
    output_file = Path(output_path)
    output_file.write_text(report_content, encoding='utf-8')
    
    # Automatically invoke Bob if requested
    remediation_path = None
    if auto_invoke_bob:
        from chaosmonkey.core.bob_integration import invoke_bob_with_fallback
        
        remediation_file = Path(output_path).parent / "CHAOS_REMEDIATION.md"
        bob_success = invoke_bob_with_fallback(
            report_path=output_file,
            output_path=remediation_file,
            timeout=bob_timeout
        )
        
        if bob_success or remediation_file.exists():
            remediation_path = str(remediation_file)
    
    return str(output_file), remediation_path


def _infer_weak_assumption(crash_report: CrashReport) -> str:
    """
    Infer the weak assumption from the crash report.
    
    Args:
        crash_report: CrashReport with error details
        
    Returns:
        Human-readable description of the suspected weak assumption
    """
    error_type = crash_report.error_type or ""
    error_message = crash_report.error_message or ""
    
    # Pattern matching for common error types
    if "AttributeError" in error_type:
        if "NoneType" in error_message:
            return "The code assumes a value is not `None`, but receives `None` at runtime. Missing null check or defensive programming."
        return "The code assumes an object has a specific attribute, but it doesn't exist at runtime."
    
    elif "KeyError" in error_type:
        return "The code assumes a dictionary key exists, but it's missing in the actual payload. Missing key validation."
    
    elif "TypeError" in error_type:
        if "subscriptable" in error_message:
            return "The code assumes a value is subscriptable (dict/list), but receives a different type (possibly None)."
        return "The code assumes a specific type, but receives a different type at runtime. Missing type validation."
    
    elif "IndexError" in error_type:
        return "The code assumes a list/array has a certain length, but it's shorter than expected. Missing bounds check."
    
    elif "ValueError" in error_type:
        return "The code assumes a value is in a valid format or range, but receives invalid data. Missing input validation."
    
    elif "ZeroDivisionError" in error_type:
        return "The code performs division without checking if the divisor is zero. Missing zero check."
    
    else:
        return f"The code makes an assumption that fails with the given input. Error: {error_type}"


# Made with Bob